### ISSUE TITLE
Job failed to load: uninitialized constant Syck::Syck. Try to manually require the required file.

### ISSUE THREAD

**Issue by titame** [instructure/canvas-jobs#1]
In my code I want to process one method call as background job which sends SMS using Twilio API.
Job is properly getting enqueued but while processing somehow delayed job is not able to deserialize that job and giving following error:

```
Job failed to load: uninitialized constant Syck::Syck. Try to manually require the required file.
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/backend/base.rb:296:in `rescue in deserialize'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/backend/base.rb:283:in `deserialize'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/backend/base.rb:185:in `payload_object'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/backend/base.rb:190:in `name'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:128:in `block in perform'
/home/varun/work/canvas-lms/config/initializers/delayed_job.rb:68:in `call'
/home/varun/work/canvas-lms/config/initializers/delayed_job.rb:68:in `block (2 levels) in <top (required)>'
/home/varun/work/canvas-lms/gems/canvas_statsd/lib/canvas_statsd/statsd.rb:75:in `time'
/home/varun/work/canvas-lms/config/initializers/delayed_job.rb:67:in `block in <top (required)>'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:78:in `call'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:78:in `block (2 levels) in add'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:60:in `call'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:60:in `block in initialize'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:78:in `call'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:78:in `block in add'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:65:in `call'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:65:in `execute'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:127:in `perform'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:102:in `block in run'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:194:in `configure_for_job'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:101:in `run'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:78:in `block in start'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:77:in `loop'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/worker.rb:77:in `start'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:156:in `block in spawn_worker'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:167:in `block in fork_with_reconnects'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:164:in `fork'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:164:in `fork_with_reconnects'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:155:in `spawn_worker'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:143:in `block (2 levels) in spawn_all_workers'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:143:in `times'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:143:in `block in spawn_all_workers'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:141:in `each'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:141:in `spawn_all_workers'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:103:in `start'
/home/varun/.rvm/gems/ruby-2.0.0-p353@canvas-lms/gems/canvas-jobs-0.9.8/lib/delayed/pool.rb:52:in `run'
script/delayed_job:10:in `<main>'
```

This is my code:

```
+  attr_reader :client, :sender, :recepient, :message
+
+  def initialize(recipient_ph_number, message_details)
+    @client = Twilio::REST::Client.new ACCOUNT_SID, AUTH_TOKEN
+    @sender = TWILIO_PHONE_NUMBER
+    @recepient = recipient_ph_number
+    @message = set_message(message_details).gsub(/[\s]{2,}/, ' ')
+  end
+
+  def send_sms
+    begin
+      client.account.messages.create(
+        :from => sender,
+        :to => "+#{recepient}",
+        :body => message
+      )
+      Rails.logger.info "---------Sent sms to #{recepient}--------"
+    rescue Twilio::REST::RequestError => e
+      Rails.logger.info "------#{e.message}-----"
+    end
+  end
+
+  handle_asynchronously :send_sms
```
All 3 constants above are initialized from key- values in yml file.
I tried with ruby 1.9.3p484 and ruby 2.0.0p353 and rails version is 3.2.21.
Also I am using syck parser for yaml.

Am I missing something?

Thanks

**Comment by ccutrer** [comment]
Ruby 2.0 is not supported. Please use ruby 1.9.3 if you're on an older release of Canvas, or Ruby 2.1 if you're on the latest stable.
